[package]
name = "chronovote"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ed25519-dalek = "2.1.1"
base64 = "0.22"
rust_decimal = "1.33"
log = "0.4"
env_logger = "0.11.8"